import {
  Activity,
  ArrowRight,
  BellRing,
  Check,
  ChevronLeft,
  CircleAlert,
  Filter,
  Gauge,
  Layers3,
  MessageSquareText,
  Send,
  SlidersHorizontal,
  Tags,
  UsersRound,
} from "lucide-react";
import { Link } from "wouter";

const logoUrl = "/manus-storage/lumae-logo-mark_b397bb7a.png";

const features = [
  { icon: MessageSquareText, name: "Survey studio", eyebrow: "Collect with clarity", copy: "Start with NPS, CSAT, CES, or a custom programme. Use simple controls to shape questions, channels, branding, and timing without making the customer work harder." },
  { icon: Send, name: "Journey delivery", eyebrow: "Reach the right moment", copy: "Deliver feedback requests by email, SMS, in-app, and QR. Frequency safeguards and delivery health keep every programme respectful and measurable." },
  { icon: Activity, name: "Live response intelligence", eyebrow: "Understand in context", copy: "See score movement, response volume, themes, and individual comments as they arrive. Filter every view by the journey, customer, location, and team that matters." },
  { icon: BellRing, name: "Recovery workflow", eyebrow: "Turn signals into ownership", copy: "Route detractor feedback to the person who can resolve it. Track acknowledgement, action, and outcome without losing the customer’s context." },
  { icon: Filter, name: "Segments and reporting", eyebrow: "Make change visible", copy: "Move from an aggregate score to evidence your stakeholders can use. Compare periods, save meaningful segments, and share a clear view of what needs attention." },
  { icon: UsersRound, name: "Teams and governance", eyebrow: "Scale without losing trust", copy: "Use roles, brand controls, access settings, and audit-friendly workflows to give people just enough customer context to act responsibly." },
];

function BrandLockup({ inverse = false }: { inverse?: boolean }) {
  return <div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center overflow-hidden rounded-xl bg-white shadow-[0_2px_12px_rgba(16,40,59,0.12)]"><img src={logoUrl} alt="" className="h-7 w-7 object-contain" /></span><span className={`text-[1.35rem] font-extrabold tracking-[-0.075em] ${inverse ? "text-white" : "text-[#10283B]"}`}>lumae</span></div>;
}

function DashboardMockup() {
  return <div className="relative overflow-hidden rounded-[30px] border border-[#10283B]/12 bg-[#10283B] p-3 shadow-[0_28px_65px_rgba(16,40,59,0.2)] sm:p-5">
    <div className="rounded-[21px] bg-[#FBFAF7] p-4 sm:p-6">
      <div className="flex items-center justify-between border-b border-[#10283B]/10 pb-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#10283B]"><img src={logoUrl} alt="" className="h-6 w-6 object-contain" /></span><div><p className="text-xs font-extrabold">Customer pulse</p><p className="mt-0.5 font-mono text-[9px] uppercase tracking-[0.12em] text-[#486170]">All journeys · last 30 days</p></div></div><button className="rounded-lg bg-[#10283B] px-3 py-2 text-[10px] font-bold text-white">Create survey</button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#E9F0F0] p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#486170]">Relationship NPS</p><p className="mt-2 text-3xl font-extrabold tracking-[-0.07em]">+42</p><p className="mt-1 text-[10px] font-bold text-[#0E867E]">+6.4 vs prior period</p></div><div className="rounded-2xl border border-[#10283B]/8 bg-white p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#486170]">Response rate</p><p className="mt-2 text-3xl font-extrabold tracking-[-0.07em]">28.6%</p><p className="mt-1 text-[10px] font-bold text-[#0E867E]">On track</p></div><div className="rounded-2xl border border-[#E96E59]/25 bg-[#fff5f2] p-4"><p className="font-mono text-[9px] uppercase tracking-[0.12em] text-[#486170]">Needs a reply</p><p className="mt-2 text-3xl font-extrabold tracking-[-0.07em]">14</p><p className="mt-1 text-[10px] font-bold text-[#E96E59]">2 new today</p></div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-2xl border border-[#10283B]/8 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs font-extrabold">Score movement</p><span className="font-mono text-[9px] text-[#486170]">WEEKLY</span></div><div className="mt-5 flex h-28 items-end gap-2">{[28, 35, 42, 38, 48, 57, 49, 65, 61, 74, 69, 88].map((height, index) => <span key={index} className={`flex-1 rounded-t-sm ${index >= 9 ? "bg-[#0E867E]" : "bg-[#b9cfcd]"}`} style={{ height: `${height}%` }} />)}</div><div className="mt-3 flex justify-between font-mono text-[9px] text-[#486170]"><span>14 MAY</span><span>14 JUN</span></div></div><div className="rounded-2xl border border-[#10283B]/8 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs font-extrabold">Live responses</p><span className="h-2 w-2 rounded-full bg-[#0E867E]" /></div><div className="mt-4 space-y-3">{[["Onboarding", "Promoter", "#dff4ef", "#0E867E"], ["Support", "Detractor", "#fbe0da", "#E96E59"], ["Delivery", "Passive", "#E9F0F0", "#486170"]].map(([journey, status, bg, color]) => <div key={journey} className="flex items-center justify-between"><div><p className="text-[11px] font-bold">{journey}</p><p className="mt-0.5 text-[9px] text-[#486170]">2 min ago</p></div><span className="rounded-full px-2 py-1 font-mono text-[8px] uppercase tracking-[0.1em]" style={{ backgroundColor: bg, color }}>{status}</span></div>)}</div></div></div>
    </div>
  </div>;
}

function RecoveryMockup() {
  return <div className="rounded-[28px] border border-[#10283B]/10 bg-white p-5 shadow-[0_16px_35px_rgba(16,40,59,0.07)] sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-[#0E867E]">Response intelligence</p><h3 className="mt-2 text-xl font-extrabold tracking-[-0.045em]">One signal. One clear next owner.</h3></div><CircleAlert className="text-[#E96E59]" size={24} /></div><div className="mt-7 grid gap-3"><div className="rounded-2xl bg-[#fff5f2] p-4"><div className="flex items-start justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#E96E59]">DETRACTOR · SUPPORT</p><p className="mt-2 text-sm font-extrabold">“I had to repeat my issue to three people.”</p></div><span className="rounded-full border border-[#E96E59]/25 px-2 py-1 font-mono text-[9px] text-[#E96E59]">01</span></div></div><div className="relative ml-5 border-l border-dashed border-[#0E867E]/45 pl-6"><span className="absolute -left-[7px] top-0 h-3.5 w-3.5 rounded-full bg-[#0E867E] ring-4 ring-[#dff4ef]" /><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#486170]">AUTO-ROUTED</p><p className="mt-1 text-sm font-bold">Assigned to Casey, Support Lead</p><p className="mt-1 text-xs leading-5 text-[#486170]">Context from ticket #4012 and the account’s last three interactions follows the response.</p></div><div className="relative ml-5 border-l border-dashed border-[#0E867E]/45 pl-6"><span className="absolute -left-[7px] top-0 h-3.5 w-3.5 rounded-full bg-[#10283B] ring-4 ring-[#E9F0F0]" /><p className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#486170]">RECOVERY TASK</p><p className="mt-1 text-sm font-bold">Reply before 4:30 PM</p></div></div></div>;
}

export default function Features() {
  return <main className="min-h-screen overflow-x-hidden bg-[#FBFAF7] text-[#10283B]">
    <header className="sticky top-0 z-50 border-b border-[#10283B]/8 bg-[#FBFAF7]/92 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1280px] items-center justify-between px-5 sm:px-8"><Link href="/"><BrandLockup /></Link><nav className="hidden items-center gap-6 lg:flex"><Link href="/#why-lumae" className="text-sm font-semibold text-[#486170] hover:text-[#10283B]">Why Lumae</Link><Link href="/features" className="text-sm font-extrabold text-[#10283B]">Features</Link><Link href="/#pricing" className="text-sm font-semibold text-[#486170] hover:text-[#10283B]">Pricing</Link><Link href="/#research" className="text-sm font-semibold text-[#486170] hover:text-[#10283B]">Research</Link></nav><div className="flex items-center gap-2"><Link href="/app" className="hidden rounded-full px-4 py-2.5 text-sm font-bold text-[#10283B] sm:block">Sign in</Link><Link href="/#waitlist" className="hidden rounded-full px-4 py-2.5 text-sm font-bold text-[#10283B] sm:block">Book a Demo</Link><Link href="/#waitlist" className="rounded-full bg-[#10283B] px-4 py-2.5 text-sm font-bold text-white transition-colors hover:bg-[#0E867E]">Start Free Trial</Link></div></div></header>

    <section className="relative border-b border-[#10283B]/8"><div className="mx-auto grid max-w-[1280px] gap-12 px-5 pb-16 pt-16 sm:px-8 sm:pb-24 sm:pt-24 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><div><p className="inline-flex rounded-full border border-[#10283B]/10 bg-white px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.14em] text-[#486170]">Product capabilities</p><h1 className="mt-7 text-balance text-[3.2rem] font-extrabold leading-[0.98] tracking-[-0.075em] sm:text-[4.6rem]">A clearer path from <span className="text-[#0E867E]">signal</span> to action.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#486170]">Lumae brings customer feedback, customer context, and accountable follow-through into one calm operating layer for service teams.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/#survey-preview" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#0E867E] px-6 py-4 text-sm font-extrabold text-white shadow-[0_12px_28px_rgba(14,134,126,0.18)] transition-all hover:-translate-y-0.5">Try the survey builder <ArrowRight size={17} /></Link><Link href="/#waitlist" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#10283B]/15 bg-white px-6 py-4 text-sm font-extrabold text-[#10283B]">Book a Demo <ArrowRight size={17} /></Link></div></div><DashboardMockup /></div></section>

    <section className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-2xl"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#0E867E]">From collection to recovery</p><h2 className="mt-5 text-balance text-4xl font-extrabold leading-[1.02] tracking-[-0.065em] sm:text-5xl">Purpose-built for the work behind a score.</h2><p className="mt-5 text-lg leading-8 text-[#486170]">The product is organised around the operational cycle—not a static survey dashboard. Each space exists to make a customer decision easier to take and easier to see through.</p></div><div className="mt-14 grid gap-x-8 md:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, name, eyebrow, copy }, index) => <article key={name} className="feature-card rounded-2xl border-t border-[#10283B]/12 p-5 py-7"><div className="flex items-center justify-between"><span className="feature-icon grid h-11 w-11 place-items-center rounded-xl bg-[#E9F0F0] text-[#0E867E] transition-colors duration-150"><Icon size={21} /></span><span className="feature-eyebrow font-mono text-[10px] text-[#486170]">0{index + 1}</span></div><p className="feature-eyebrow mt-6 font-mono text-[10px] uppercase tracking-[0.14em] text-[#0E867E]">{eyebrow}</p><h3 className="feature-title mt-2 text-xl font-extrabold tracking-[-0.045em] transition-colors duration-150">{name}</h3><p className="mt-3 text-sm leading-6 text-[#486170]">{copy}</p></article>)}</div></section>

    <section className="border-y border-[#10283B]/8 bg-[#E9F0F0] py-20 sm:py-28"><div className="mx-auto grid max-w-[1160px] gap-12 px-5 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#0E867E]">Close the loop</p><h2 className="mt-5 text-balance text-4xl font-extrabold leading-[1.02] tracking-[-0.065em] sm:text-5xl">Let the right person see the customer context.</h2><p className="mt-6 text-lg leading-8 text-[#486170]">A detractor is not a workflow. Lumae turns a response into a focused action with the relevant history, responsible owner, and recovery moment in one visible view.</p><div className="mt-8 space-y-3">{[["Detect", "Know when a response needs attention."], ["Route", "Send it to the right person with context."], ["Recover", "Make the next customer interaction visible."]].map(([title, copy]) => <div key={title} className="flex gap-3"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#0E867E] text-[11px] font-extrabold text-white"><Check size={13} /></span><p className="text-sm leading-6 text-[#486170]"><strong className="text-[#10283B]">{title}.</strong> {copy}</p></div>)}</div></div><RecoveryMockup /></div></section>

    <section className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 sm:py-28"><div className="rounded-[32px] bg-[#10283B] p-6 text-white sm:p-10"><div className="grid gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#69d7ce]">Designed to integrate</p><h2 className="mt-5 text-balance text-4xl font-extrabold leading-[1.02] tracking-[-0.065em]">Keep feedback connected to the work your team already does.</h2><p className="mt-5 text-base leading-7 text-white/68">The future platform blueprint includes CRM, helpdesk, and API integration pathways so response context can travel to the systems where service, account, and product decisions happen.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[{ icon: Layers3, label: "CRM context" }, { icon: Tags, label: "Feedback tags" }, { icon: SlidersHorizontal, label: "Saved segments" }, { icon: Gauge, label: "Trend reports" }, { icon: UsersRound, label: "Role access" }, { icon: Send, label: "Journey triggers" }].map(({ icon: Icon, label }) => <div key={label} className="rounded-2xl border border-white/12 bg-white/[0.05] p-5"><Icon size={22} /><p className="mt-8 text-sm font-extrabold">{label}</p></div>)}</div></div></div></section>

    <section className="bg-[#0E867E] py-20 text-white sm:py-24"><div className="mx-auto flex max-w-[1040px] flex-col items-start justify-between gap-8 px-5 sm:px-8 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/65">See the product direction</p><h2 className="mt-4 max-w-xl text-balance text-4xl font-extrabold leading-[1.02] tracking-[-0.065em]">Try the interactive survey-builder preview.</h2></div><Link href="/#survey-preview" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-4 text-sm font-extrabold text-[#10283B] shadow-sm transition-transform hover:-translate-y-0.5">Open preview <ArrowRight size={17} /></Link></div></section>

    <footer className="bg-[#FBFAF7] py-10"><div className="mx-auto flex max-w-[1280px] flex-col justify-between gap-6 px-5 sm:px-8 md:flex-row md:items-center"><Link href="/"><BrandLockup /></Link><div className="flex gap-6 text-sm font-semibold text-[#486170]"><Link href="/">Home</Link><Link href="/#pricing">Pricing</Link><Link href="/#waitlist">Early access</Link></div><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#0E867E]"><ChevronLeft size={16} /> Back to home</Link></div></footer>
  </main>;
}
