import { AppPageHeader } from "@/components/LumaeAppShell";
import { trpc } from "@/lib/trpc";
import { Check, ChevronLeft, ClipboardList, Eye, Plus, Send, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation, useRoute } from "wouter";

const surveyTypes = [
  { value: "nps", label: "NPS", helper: "Relationship recommendation" },
  { value: "csat", label: "CSAT", helper: "Moment-level satisfaction" },
  { value: "ces", label: "CES", helper: "Ease of getting help" },
  { value: "custom", label: "Custom", helper: "Your own question" },
] as const;
type SurveyType = (typeof surveyTypes)[number]["value"];
const defaults: Record<SurveyType, string> = { nps: "How likely are you to recommend us to a colleague or friend?", csat: "How satisfied were you with your experience today?", ces: "How easy was it to get the help you needed today?", custom: "What would you like us to understand about your experience?" };

export function SurveyList() {
  const surveys = trpc.surveys.list.useQuery();
  const [, setLocation] = useLocation();
  return <div className="space-y-8"><AppPageHeader eyebrow="Survey studio" title="Build moments worth listening to."><button onClick={() => setLocation("/app/surveys/new")} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#0e867e] px-4 text-sm font-bold text-white"><Plus className="h-4 w-4" />New survey</button></AppPageHeader><section className="rounded-[28px] border border-[#dce7e7] bg-white">{surveys.isLoading ? <div className="h-52 animate-pulse bg-[#e9f0f0]" /> : surveys.data?.length ? <div className="divide-y divide-[#e9f0f0]">{surveys.data.map(survey => <button key={survey.id} onClick={() => setLocation(`/app/surveys/${survey.id}`)} className="flex w-full items-center gap-4 px-6 py-5 text-left transition-colors hover:bg-[#fbfaf7]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9f0f0] text-[#0e867e]"><ClipboardList className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="truncate font-bold">{survey.name}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.14em] text-[#486170]">{survey.surveyType} · {survey.status}</p></div><ChevronLeft className="h-4 w-4 rotate-180 text-[#0e867e]" /></button>)}</div> : <div className="px-6 py-16 text-center"><ClipboardList className="mx-auto h-7 w-7 text-[#0e867e]" /><h2 className="mt-4 text-xl font-extrabold tracking-[-0.04em]">Start with one customer moment.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#486170]">Create a draft, make the question useful, and publish it only when your delivery settings are ready.</p><button onClick={() => setLocation("/app/surveys/new")} className="mt-6 inline-flex h-10 items-center rounded-xl bg-[#10283b] px-4 text-sm font-bold text-white">Create a survey</button></div>}</section></div>;
}

export function SurveyBuilder() {
  const utils = trpc.useUtils();
  const [, setLocation] = useLocation();
  const [surveyType, setSurveyType] = useState<SurveyType>("csat");
  const [name, setName] = useState("Support follow-up");
  const [question, setQuestion] = useState(defaults.csat);
  const [introductionText, setIntroductionText] = useState("Your response helps us improve the experience for everyone.");
  const create = trpc.surveys.create.useMutation({ onSuccess: async result => { await utils.surveys.list.invalidate(); if (result?.survey) setLocation(`/app/surveys/${result.survey.id}`); } });
  const scale = surveyType === "nps" ? 11 : surveyType === "custom" ? 0 : 5;
  return <div className="space-y-8"><AppPageHeader eyebrow="Survey studio" title="Create a useful customer moment"><button onClick={() => setLocation("/app/surveys")} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#cfdcdd] bg-white px-4 text-sm font-bold text-[#10283b]"><ChevronLeft className="h-4 w-4" />Back to surveys</button></AppPageHeader><div className="grid gap-6 xl:grid-cols-[1fr_0.82fr]"><form onSubmit={event => { event.preventDefault(); create.mutate({ name, surveyType, questionText: question, introductionText }); }} className="rounded-[28px] border border-[#dce7e7] bg-white p-6 sm:p-8"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#0e867e]">1 · Define the signal</p><label className="mt-6 grid gap-2 text-sm font-bold">Survey name<input value={name} onChange={event => setName(event.target.value)} className="h-12 rounded-xl border border-[#cfdcdd] bg-[#fbfaf7] px-4 font-normal outline-none focus:border-[#0e867e]" /></label><div className="mt-6 grid gap-3 sm:grid-cols-2">{surveyTypes.map(type => <button type="button" key={type.value} onClick={() => { setSurveyType(type.value); setQuestion(defaults[type.value]); }} className={`rounded-2xl border p-4 text-left transition-colors ${surveyType === type.value ? "border-[#0e867e] bg-[#e9f0f0]" : "border-[#dce7e7] hover:bg-[#fbfaf7]"}`}><p className="font-bold">{type.label}</p><p className="mt-1 text-xs text-[#486170]">{type.helper}</p></button>)}</div><label className="mt-6 grid gap-2 text-sm font-bold">Question<textarea value={question} onChange={event => setQuestion(event.target.value)} rows={3} className="rounded-xl border border-[#cfdcdd] bg-[#fbfaf7] px-4 py-3 font-normal leading-6 outline-none focus:border-[#0e867e]" /></label><label className="mt-6 grid gap-2 text-sm font-bold">Introductory note <span className="font-normal text-[#486170]">optional</span><textarea value={introductionText} onChange={event => setIntroductionText(event.target.value)} rows={3} className="rounded-xl border border-[#cfdcdd] bg-[#fbfaf7] px-4 py-3 font-normal leading-6 outline-none focus:border-[#0e867e]" /></label>{create.error && <p className="mt-4 text-sm text-[#e96e59]">{create.error.message}</p>}<button disabled={create.isPending} className="mt-7 inline-flex h-11 items-center gap-2 rounded-xl bg-[#0e867e] px-5 text-sm font-bold text-white disabled:opacity-60">{create.isPending ? "Saving draft…" : "Save draft"}<Check className="h-4 w-4" /></button></form><SurveyPreview question={question} introduction={introductionText} scale={scale} type={surveyType} /></div></div>;
}

function SurveyPreview({ question, introduction, scale, type }: { question: string; introduction: string; scale: number; type: SurveyType }) {
  const values = useMemo(() => Array.from({ length: scale }, (_, index) => index + (type === "nps" ? 0 : 1)), [scale, type]);
  return <aside className="rounded-[28px] bg-[#10283b] p-6 text-white sm:p-8"><div className="flex items-center gap-2 text-[#69d7ce]"><Eye className="h-4 w-4" /><span className="font-mono text-[10px] uppercase tracking-[0.16em]">Mobile-first preview</span></div><div className="mt-7 rounded-[24px] bg-white p-5 text-[#10283b] shadow-2xl"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#e9f0f0]"><img src="/manus-storage/lumae-logo-mark_b397bb7a.png" alt="" className="h-4 w-4" /></span><span className="font-extrabold tracking-[-0.05em]">lumae</span></div><p className="mt-7 font-mono text-[10px] uppercase tracking-[0.16em] text-[#0e867e]">{type} question</p><h2 className="mt-3 text-xl font-extrabold leading-[1.15] tracking-[-0.045em]">{question || "Your survey question"}</h2>{introduction && <p className="mt-3 text-sm leading-6 text-[#486170]">{introduction}</p>}{scale ? <div className={`mt-7 grid gap-1 ${scale > 5 ? "grid-cols-6" : "grid-cols-5"}`}>{values.map(value => <span className="grid aspect-square place-items-center rounded-lg border border-[#cfdcdd] text-xs font-bold" key={value}>{value}</span>)}</div> : <div className="mt-7 h-20 rounded-xl border border-dashed border-[#cfdcdd] bg-[#fbfaf7]" />}<button className="mt-7 h-10 w-full rounded-xl bg-[#0e867e] text-sm font-bold text-white">Continue</button></div></aside>;
}

export function SurveyDetail() {
  const [, params] = useRoute("/app/surveys/:id");
  const [, setLocation] = useLocation();
  const surveyId = Number(params?.id);
  const utils = trpc.useUtils();
  const detail = trpc.surveys.detail.useQuery({ surveyId }, { enabled: Number.isFinite(surveyId) });
  const publish = trpc.surveys.publish.useMutation({ onSuccess: async () => { await utils.surveys.detail.invalidate({ surveyId }); await utils.surveys.list.invalidate(); await utils.workspace.dashboard.invalidate(); } });
  if (detail.isLoading) return <div className="h-64 animate-pulse rounded-[28px] bg-[#e9f0f0]" />;
  if (!detail.data) return <div className="rounded-[28px] bg-white p-8">Survey not found.</div>;
  const question = detail.data.questions[0];
  return <div className="space-y-8"><AppPageHeader eyebrow={`Survey studio · ${detail.data.survey.surveyType}`} title={detail.data.survey.name}><button onClick={() => setLocation("/app/surveys")} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#cfdcdd] bg-white px-4 text-sm font-bold"><ChevronLeft className="h-4 w-4" />Library</button>{detail.data.survey.status !== "published" && <button onClick={() => publish.mutate({ surveyId })} disabled={publish.isPending} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#0e867e] px-4 text-sm font-bold text-white"><Send className="h-4 w-4" />{publish.isPending ? "Publishing…" : "Publish survey"}</button>}</AppPageHeader><div className="grid gap-6 lg:grid-cols-[1fr_0.7fr]"><section className="rounded-[28px] border border-[#dce7e7] bg-white p-7"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#0e867e]">Question 01</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.045em]">{question?.prompt}</h2><p className="mt-5 text-sm leading-6 text-[#486170]">This is a persisted {detail.data.survey.surveyType.toUpperCase()} survey draft. Publish it when you are ready to configure a journey and delivery channel.</p></section><section className="rounded-[28px] bg-[#e9f0f0] p-7"><Sparkles className="h-6 w-6 text-[#0e867e]" /><h2 className="mt-5 text-xl font-extrabold tracking-[-0.045em]">Delivery is intentional.</h2><p className="mt-3 text-sm leading-6 text-[#486170]">Email, SMS, in-app, and QR journeys can be planned now. Provider configuration is required before any message can be sent.</p><p className="mt-6 font-mono text-[10px] uppercase tracking-[0.16em] text-[#486170]">Status · {detail.data.survey.status}</p></section></div>{detail.data.survey.status === "published" && <JourneyPlanner surveyId={surveyId} />}</div>;
}

function JourneyPlanner({ surveyId }: { surveyId: number }) {
  const utils = trpc.useUtils();
  const journeys = trpc.journeys.listForSurvey.useQuery({ surveyId });
  const [name, setName] = useState("Post-interaction follow-up");
  const [channel, setChannel] = useState<"email" | "sms" | "in_app" | "qr">("email");
  const create = trpc.journeys.create.useMutation({ onSuccess: async () => { await utils.journeys.listForSurvey.invalidate({ surveyId }); } });
  return <section className="rounded-[28px] border border-[#dce7e7] bg-white p-6 sm:p-7"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#0e867e]">Journey planning</p><h2 className="mt-2 text-2xl font-extrabold tracking-[-0.045em]">Plan the moment you will ask.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#486170]">A journey captures delivery intent and a frequency safeguard. It does not send any communication until a provider is connected.</p><form className="mt-6 grid gap-3 md:grid-cols-[1fr_170px_auto]" onSubmit={event => { event.preventDefault(); create.mutate({ surveyId, name, channel, triggerType: "manual", frequencyGuardDays: 30 }); }}><input value={name} onChange={event => setName(event.target.value)} className="h-11 rounded-xl border border-[#cfdcdd] bg-[#fbfaf7] px-4 text-sm outline-none focus:border-[#0e867e]" aria-label="Journey name" /><select value={channel} onChange={event => setChannel(event.target.value as typeof channel)} className="h-11 rounded-xl border border-[#cfdcdd] bg-[#fbfaf7] px-4 text-sm outline-none focus:border-[#0e867e]"><option value="email">Email</option><option value="sms">SMS</option><option value="in_app">In-app</option><option value="qr">QR</option></select><button disabled={create.isPending} className="h-11 rounded-xl bg-[#10283b] px-4 text-sm font-bold text-white disabled:opacity-60">{create.isPending ? "Saving…" : "Save journey"}</button></form>{journeys.data?.length ? <div className="mt-6 divide-y divide-[#e9f0f0] rounded-2xl border border-[#e9f0f0]">{journeys.data.map(journey => <div key={journey.id} className="flex items-center justify-between px-4 py-3"><div><p className="text-sm font-bold">{journey.name}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.14em] text-[#486170]">{journey.channel} · {journey.frequencyGuardDays}-day guard</p></div><span className="rounded-full bg-[#e9f0f0] px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.12em] text-[#486170]">{journey.status}</span></div>)}</div> : <p className="mt-5 text-sm text-[#486170]">No journeys planned for this survey yet.</p>}</section>;
}
